# File: run_funda_scraper_lite.py
import json
import sqlite3
import logging
from pathlib import Path
from typing import List
import asyncio

from funda_scraper import FundaScraper
from telegram import Bot  # pip install python‑telegram‑bot

# -------------------------------------------------
# 1️⃣  Load already‑known URLs from the DB
# -------------------------------------------------
DB_PATH = Path("db/listings.db")
KNOWN_TABLE = "known_urls"

def get_known_urls() -> List[str]:
    """Return a list of URLs that were already processed."""
    if not DB_PATH.exists():
        logging.warning('No DB found')
        return []
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    # Create table if it does not exist (first run)
    cur.execute(
        f"""CREATE TABLE IF NOT EXISTS {KNOWN_TABLE} (
                url TEXT PRIMARY KEY
            )"""
    )
    cur.execute(f"SELECT url FROM {KNOWN_TABLE}")
    rows = cur.fetchall()
    conn.close()
    return [r[0] for r in rows]

def store_new_urls(urls: List[str]) -> None:
    """Persist newly‑found URLs so they won’t be re‑sent next time."""
    if not urls:
        return
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.executemany(
        f"INSERT OR IGNORE INTO {KNOWN_TABLE} (url) VALUES (?)",
        [(u,) for u in urls],
    )
    conn.commit()
    conn.close()

# -------------------------------------------------
# 2️⃣  Initialise the scraper with the known list
# -------------------------------------------------
logging.basicConfig(level=logging.INFO)


known = get_known_urls()

scraper = FundaScraper(
        area="amsterdam,5km",
        want_to="buy",
        find_past=False,
        page_start=1,
        n_pages=1,
        min_price=300000,
        max_price=400000,
        min_floor_area=40,
        extra_args={
            'energy_label': '%5B%22A%2B%2B%2B%2B%2B%22,%22A%2B%2B%2B%2B%22,%22A%2B%2B%2B%22,%22A%2B%2B%22,%22A%2B%22,%22A%22,%22B%22,%22C%22%5D',
            'sort': '%22date_down%22'
        },
        known_urls=known,
    )

# -------------------------------------------------
# 3️⃣  Run the scraper – it will fill `scraper.links` only
#     with URLs that are **not** in `known`
# -------------------------------------------------
scraper.fetch_all_links()
new_links = scraper.links
logging.info(f"Found {len(new_links)} brand‑new listings.")

# -------------------------------------------------
# 4️⃣  Limit the batch that goes to Telegram
# -------------------------------------------------
if not new_links:
    logging.info("No new listings – nothing to send.")
    exit(0)

# Load your Telegram credentials (generated by BotFather)
with open("telegram_config.json") as f:
    tg_cfg = json.load(f)

bot = Bot(tg_cfg["api_key"])
group_id = tg_cfg["group_id"]      # <-- make sure this key exists in the JSON

MAX_NEW_TO_SEND = 5

async def send_new_houses_to_telegram():
    # Send at most `MAX_NEW_TO_SEND` messages
    for link in new_links[:MAX_NEW_TO_SEND]:
        await bot.send_message(chat_id=group_id, text=f"🆕 New Funda listing: {link}")

asyncio.run(send_new_houses_to_telegram())

# -------------------------------------------------
# 5️⃣  Persist *all* newly discovered URLs (even the ones we didn’t send)
# -------------------------------------------------
# store_new_urls(new_links)

logging.info("Run complete.")